---
- name: Updating the repo and cache
  apt:
    update_cache: yes
  register: result
  until: result is succeeded
  retries: 5
  delay: 5

- name: Creating user for alertmanager
  user:
    name: prom
    shell: /sbin/nologin

- name: Download and install Unzip and Systemd
  apt:
    name: ['unzip', 'systemd']
    state: present

- name: Setting internal variables for convinience
  set_fact:
    base_url: "https://github.com/prometheus/alertmanager/releases/download"

- name: Downloading the binary file for Alertmanager
  unarchive:
    src: "{{ base_url }}/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    mode: 0755

- name: Move the binary executable file
  copy: 
    src: /tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager
    dest: /usr/local/bin/
    mode: 0555
    remote_src: yes

- name: Create Data and Configuration Directory for Alertmanager
  file:
    path: "{{ item }}"
    state: directory
    owner: prom
    group: prom
  with_items:
    - /var/lib/alertmanager
    - /etc/alertmanager

- name: Adding Alertmanager Configuration
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    mode: 0754

- name: Adding Email Template for Alertmanager
  copy:
    src: email.tmpl
    dest: /etc/alertmanager/email.tmpl
    mode: 0754

- name: Copy Service for Alertmanager
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
  notify:
    - reload_alertmanager_service
    - restart_alertmanager_service
