---
# tasks file for alertmanager
- name: Install Alertmanager on Debian
  include_tasks: debian.yml
  when:
    ansible_os_family == "Debian"

- name: Install Alertmanager on RedHat
  include_tasks: redhat.yml
  when:
    ansible_os_family == "RedHat"
