---
- name: Creating user for alertmanager
  user:
    name: prom
    shell: /sbin/nologin

- name: Installing unzip and libselinux-python
  yum:
    name: ['unzip', 'libselinux-python']
    state: present
  register: result
  until: result is succeeded
  retries: 5
  delay: 5

- name: Installing Systemd on Centos
  yum:
    name: systemd
    state: present
  when:
    ansible_distribution_major_version == "7"

- name: Setting internal variables for convinience
  set_fact:
    base_url: "https://github.com/prometheus/alertmanager/releases/download"

- name: Downloading the binary file for Alertmanager
  unarchive:
    src: "{{ base_url }}/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    mode: 0755

- name: Move the binary executable file
  copy: 
    src: /opt/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager
    dest: /usr/local/bin/
    mode: 0555
    remote_src: yes

- name: Copy init script of Alertmanager for Centos 6
  copy:
    src: alertmanager.init
    dest: /etc/init.d/alertmanager
    mode: 0555
  when:
    ansible_distribution_major_version == "6"

- name: Create directory for Alertmanager Configuration, Data and Logs
  file:
    path: "{{ item }}"
    state: directory
    owner: prom
    group: prom
  with_items:
    - /etc/alertmanager
    - /var/lib/alertmanager
    - /var/log/alertmanager

- name: Adding Alertmanager Configuration
  template:
    src: alertmanager.yml.j2
    dest: /etc/alertmanager/alertmanager.yml
    mode: 0754

- name: Adding Email Template for Alertmanager
  copy:
    src: email.tmpl
    dest: /etc/alertmanager/email.tmpl
    mode: 0754

- name: Copy Service for Prometheus
  template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    mode: 0755
  notify:
    - reload_alertmanager_service
    - restart_alertmanager_service
  when:
    ansible_distribution_major_version == "7"

- name: Restarting the init alertmanager service
  service: 
    name: alertmanager
    state: started
  when:
    ansible_distribution_major_version == "6"
